version: "3.6"

services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  graphql-engine:
    build:
      context: .
      dockerfile: ./Dockerfile.hasura
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE=false
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
    #volumes:
    # - ./lib/metadata:/hasura-metadata
    #- ./lib/migrations:/hasura-migrations
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - "graphql-engine"
volumes:
  db_data:
